base_model: yanolja/EEVE-Korean-10.8B-v1.0
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

trust_remote_code: True

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: indentcorp-data/one_by_one_with_english-alpaca_chat_load_qa
    type: alpaca_chat.load_qa
    train_on_split: train

test_datasets:
  - path: indentcorp-data/one_by_one_with_english-alpaca_chat_load_qa
    type: alpaca_chat.load_qa
    split: validation

dataset_prepared_path:
output_dir: ./lora-out

sequence_len: 512
sample_packing: false
pad_to_sequence_len:

adapter: qlora
lora_model_dir:
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out: false
lora_target_modules:
  - q_proj
  - v_proj

wandb_project: qlora_eeve
wandb_entity:
wandb_watch:
wandb_name: qlora_eeve
wandb_log_model:

mlflow_experiment:
mlflow_tracking_uri:

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention:

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:

flash_attention: false

special_tokens:
  bos_token: "<s>"
  eos_token: "<|im_end|>"
  pad_token: "</s>"
  unk_token: "<unk>"

seed: 42